const item1 = {
  user: {
    id: 1,
    name: '一个数据很长的人',
    student_id: '2021211222',
    class_id: '2021211333',
    college: '计算机学院（国家示范性软件学院）',
  },
  overall: [
    { category: '参与活动总量', count: 117 },
    { category: '思想成长', count: 14 },
    { category: '社会实践', count: 15 },
    { category: '志愿服务', count: 18 },
    { category: '学术科创', count: 17 },
    { category: '文化艺术', count: 19 },
    { category: '强身健体', count: 14 },
    { category: '其他', count: 20 },
  ],
  semesters: [
    {
      semester: '2021-2022-1',
      acts: [
        {
          id: 0,
          name: '“科技﹣产业﹣金融”AI时代下的生涯规划职业发展交流会',
          category: '思想成长',
          type: 2,
        },
        {
          id: 1,
          name: '“传承五四精神，凝聚榜样力量”观影活动',
          category: '社会实践',
          type: 3,
        },
        { id: 2, name: '全国大学生数学竞赛', category: '社会实践', type: 2 },
        {
          id: 3,
          name: '北京邮电大学第三十二届“一二·九”火炬接力赛',
          category: '社会实践',
          type: 3,
        },
        {
          id: 4,
          name: '计算机学院本科5月13日天安门升国旗仪式',
          category: '志愿服务',
          type: 1,
        },
        { id: 5, name: '2022级体育比赛之“校长杯”足球赛', category: '志愿服务', type: 1 },
        { id: 6, name: '校级第七届宿舍文化节', category: '志愿服务', type: 3 },
        {
          id: 7,
          name: '计算机学院本科22级党支部学业辅导组离散数学知识点期中串讲与答疑活动',
          category: '志愿服务',
          type: 3,
        },
        { id: 8, name: '华为ict大赛', category: '学术科创', type: 3 },
        { id: 9, name: '2022级校院升旗仪式', category: '学术科创', type: 2 },
        {
          id: 10,
          name: '计算机学院2022级党支部铲雪劳动实践活动',
          category: '学术科创',
          type: 3,
        },
        {
          id: 11,
          name: '“以水促和谐”--2024年校园节水宣传活动',
          category: '学术科创',
          type: 1,
        },
        { id: 12, name: '2023蓝图加速器活动', category: '学术科创', type: 3 },
        { id: 13, name: '雏雁计划（单人）', category: '文化艺术', type: 3 },
        {
          id: 14,
          name: '北京邮电大学第十六届“明日之星”英语风采大赛',
          category: '文化艺术',
          type: 3,
        },
        { id: 15, name: '2022级其他各类心理活动', category: '强身健体', type: 3 },
        { id: 16, name: '北京市大学生书法大赛校内征稿', category: '强身健体', type: 1 },
        {
          id: 17,
          name: '第十季“你选书 我买单”——中华优秀传统文化主题系列之四',
          category: '强身健体',
          type: 1,
        },
        { id: 18, name: '雏雁计划（团队）', category: '其他', type: 2 },
        { id: 19, name: '其他校级个人艺术类活动', category: '其他', type: 2 },
        {
          id: 20,
          name: '世纪讲坛第161讲——数字贸易激活贸易发展新动能',
          category: '其他',
          type: 1,
        },
        { id: 21, name: '”医邮合作，健康传递”手诊活动', category: '其他', type: 3 },
        { id: 22, name: '2022级田径队院队成员', category: '其他', type: 2 },
      ],
    },
    {
      semester: '2021-2022-2',
      acts: [
        { id: 0, name: '北京邮电大学9月1日升旗天安门', category: '思想成长', type: 2 },
        {
          id: 1,
          name: '2022级“增知拓径 计导未来”学院企业参 观系列活动',
          category: '思想成长',
          type: 1,
        },
        {
          id: 2,
          name: '2022级首都大学、中职院校“先锋杯”优秀基层团支部创建',
          category: '思想成长',
          type: 2,
        },
        {
          id: 3,
          name: '“AI在邮苑·共戏舞林”三校联谊秋季舞会',
          category: '社会实践',
          type: 3,
        },
        { id: 4, name: '学长学姐座谈会', category: '社会实践', type: 3 },
        { id: 5, name: '校级公众号推送作品征集', category: '志愿服务', type: 2 },
        {
          id: 6,
          name: '2022级校园十佳学生心理骨干评选活动',
          category: '志愿服务',
          type: 1,
        },
        { id: 7, name: '2022级校级优秀团支部评选', category: '学术科创', type: 2 },
        {
          id: 8,
          name: '计算机学院2022级党支部“宪法知识小竞赛”',
          category: '文化艺术',
          type: 1,
        },
        {
          id: 9,
          name: '2022级学院评 选中获奖的优秀团日活动',
          category: '文化艺术',
          type: 3,
        },
        {
          id: 10,
          name: '“推广普通话，奋进新征程”2023年北京市汉语知识闯关活动-欢迎访 问信息服务门户 (bupt.edu.cn)',
          category: '文化艺术',
          type: 3,
        },
        {
          id: 11,
          name: '计算机学院（国家示范性软件学院）国脉大讲堂第十三讲',
          category: '文化艺术',
          type: 1,
        },
        {
          id: 12,
          name: '2024年“中国高校计算机大赛-网络技术挑战赛”',
          category: '强身健体',
          type: 1,
        },
        {
          id: 13,
          name: '好“柿”当头，柿子发布会之秋韵交换照片征集',
          category: '其他',
          type: 2,
        },
        { id: 14, name: '“节约粮食，光盘行动”包饺子活动', category: '其他', type: 3 },
      ],
    },
    {
      semester: '2022-2023-1',
      acts: [
        {
          id: 0,
          name: '好“柿”当头，柿子发布会之秋韵交换照片征集',
          category: '思想成长',
          type: 3,
        },
        { id: 1, name: '校男子篮球半决赛', category: '思想成长', type: 1 },
        { id: 2, name: '大学生创新创业训练 计划（团队）', category: '社会实践', type: 3 },
        {
          id: 3,
          name: '北京邮电大学第四届“芳华杯”美育作品大赛',
          category: '社会实践',
          type: 2,
        },
        {
          id: 4,
          name: '计算机、信通 、电子联合校内快闪唱歌活动',
          category: '社会实践',
          type: 1,
        },
        {
          id: 5,
          name: '“职为邮你”就业经验 分享交流月——金融类专场',
          category: '社会实践',
          type: 3,
        },
        { id: 6, name: '“纸短情长”三行代码创意大赛', category: '社会实践', type: 2 },
        { id: 7, name: '春季游园会', category: '志愿服务', type: 3 },
        {
          id: 8,
          name: '相约《山海情》——国家大剧院歌剧走进北邮',
          category: '志愿服务',
          type: 3,
        },
        {
          id: 9,
          name: '2022级体育比赛之“校长杯”女子五人制足球赛',
          category: '志愿服务',
          type: 1,
        },
        {
          id: 10,
          name: '“香佩随身驱五害，摇风传情邮万里”——端午节父亲节活动',
          category: '志愿服务',
          type: 2,
        },
        { id: 11, name: '2022级校级其他体育比赛', category: '学术科创', type: 1 },
        { id: 12, name: '防范网络电信诈骗宣传教育交流会', category: '学术科创', type: 1 },
        {
          id: 13,
          name: '2022级国脉大讲堂校园文化育人品牌活动',
          category: '学术科创',
          type: 1,
        },
        { id: 14, name: '“秋之韵”歌手大赛', category: '学术科创', type: 3 },
        { id: 15, name: '5G全息远程互动教室现场教学', category: '学术科创', type: 2 },
        {
          id: 16,
          name: '2022级学院评选中获奖的优秀团日活动',
          category: '文化艺术',
          type: 1,
        },
        { id: 17, name: '“五月鲜花”合唱比赛', category: '文化艺术', type: 2 },
        { id: 18, name: '2022级体育活动观众之“一月一赛”', category: '文化艺术', type: 1 },
        { id: 19, name: '“学霸三部曲”作品征集活动', category: '文化艺术', type: 2 },
        {
          id: 20,
          name: '2022级体育活动观众之“南天信息杯”师生校友羽毛球赛',
          category: '文化艺术',
          type: 3,
        },
        { id: 21, name: '2022级“一二·九”火炬接力观众', category: '强身健体', type: 1 },
        {
          id: 22,
          name: '第二十六届中国机器人及人工智能大赛校赛',
          category: ' 强身健体',
          type: 3,
        },
        { id: 23, name: '2022级体育比赛之“校长杯”足球赛', category: '强身健体', type: 3 },
        {
          id: 24,
          name: '其他校院 级征文、朗诵、演讲、作品征集活动',
          category: '强身健体',
          type: 3,
        },
        { id: 25, name: '团委社会实践', category: '强身健体', type: 3 },
        { id: 26, name: '“2024体育文化节”之篮球嘉年华活动', category: '其他', type: 3 },
        { id: 27, name: '2022级校级其他体育比赛', category: '其他', type: 1 },
        { id: 28, name: '开学典礼合唱演出(西土城校区)', category: '其他', type: 2 },
        {
          id: 29,
          name: '第十九届“挑战 杯”全国大学生课外学术科技作品竞赛之“揭榜挂帅”专项赛',
          category: '其他',
          type: 2,
        },
      ],
    },
    {
      semester: '2022-2023-2',
      acts: [
        { id: 0, name: '2022级校级其他体育比赛', category: '思想成长', type: 3 },
        { id: 1, name: '大学生创新创业训练计划（单人）', category: '思想成长', type: 3 },
        { id: 2, name: '校男子足球半决赛', category: '思想成长', type: 3 },
        { id: 3, name: '2022级校级其他体育比赛', category: '思想成长', type: 3 },
        { id: 4, name: '雏雁计划（团队）', category: '思想成长', type: 1 },
        {
          id: 5,
          name: '计算机学院（国家示范性软件学院）2023~2024年度优秀团支部评选大会观众',
          category: '社会实践',
          type: 3,
        },
        { id: 6, name: '其他校级个人艺术类活动', category: '志愿服务', type: 1 },
        { id: 7, name: '“五月鲜花”合唱比赛', category: '志愿服务', type: 3 },
        { id: 8, name: '影视表演基础交流会', category: '志愿服务', type: 1 },
        { id: 9, name: '大学生创新创业训练计划（团队）', category: '学术科创', type: 1 },
        {
          id: 10,
          name: '“扇传邮意，珠慰母心—— 一珠一扇总关情”母亲节活动',
          category: '文化艺术',
          type: 3,
        },
        { id: 11, name: '2022级校级其他体育比赛', category: '文化艺术', type: 1 },
        { id: 12, name: '5.28 AI 音乐讲座', category: '文化艺术', type: 2 },
        {
          id: 13,
          name: '八强赛一 篮球赛(计算 机一队VS邮理联队)',
          category: '文化艺术',
          type: 3,
        },
        {
          id: 14,
          name: '计算机学院（国家示范性软件学院）团学组织春季联欢会',
          category: '文化艺术',
          type: 2,
        },
        {
          id: 15,
          name: '计算机学院本科22级党支部 毛概期末串讲',
          category: '强身健体',
          type: 3,
        },
        { id: 16, name: '“卓越·院长论坛”第三期讲座', category: '强身健体', type: 1 },
        {
          id: 17,
          name: '第三届全国大学生数字贸易综合技能大赛（华北赛区）',
          category: '其他',
          type: 2,
        },
        { id: 18, name: '共青团北京邮电大学第十七次代表大会', category: '其他', type: 1 },
        {
          id: 19,
          name: '2022级 心理素质教育工作优秀学生骨干评选',
          category: '其他',
          type: 3,
        },
        { id: 20, name: '2022级师生趣味运动会', category: '其他', type: 1 },
      ],
    },
    {
      semester: '2023-2024-1',
      acts: [
        {
          id: 0,
          name: '第三届全国大学生数字贸易综合技能大赛（华北赛区）',
          category: '思想成长',
          type: 1,
        },
        {
          id: 1,
          name: '月满乾坤贺中秋，星耀华夏举国庆 双节摄影大赛',
          category: '思想成长',
          type: 2,
        },
        {
          id: 2,
          name: '“云赏非遗 · 悦读春天”有奖答题活动',
          category: '思想成长',
          type: 2,
        },
        {
          id: 3,
          name: '2022级“国家安全 青春挺膺”总体国家安全观宣传教育主场示范活动',
          category: '社会实践',
          type: 3,
        },
        {
          id: 4,
          name: '第二十六届中国机器人及人工智能大赛校赛',
          category: '社会实践',
          type: 1,
        },
        {
          id: 5,
          name: '2024文化科技卫生“三下乡”活动\n优秀团队',
          category: '社会实践',
          type: 1,
        },
        { id: 6, name: '北京市大学生书法大赛校内征稿', category: '社会实践', type: 3 },
        { id: 7, name: '全国大学生数学竞赛', category: '志愿服务', type: 3 },
        { id: 8, name: '2022级校级(不含)以上体育比赛', category: '志愿服务', type: 2 },
        { id: 9, name: '“艺馨杯”文艺汇演', category: '志愿服务', type: 1 },
        {
          id: 10,
          name: '2022级学院评选中获奖的优秀班集体',
          category: '志愿服务',
          type: 3,
        },
        {
          id: 11,
          name: '北京邮电大学第三十六届校园歌手大赛决赛',
          category: '志愿服务',
          type: 3,
        },
        { id: 12, name: '“一二·九”艺馨杯文艺展演', category: '学术科创', type: 2 },
        {
          id: 13,
          name: '2023“外研 社.国才杯”“理解当代中国”全国大学生外语能力竞赛',
          category: '学术科创',
          type: 3,
        },
        {
          id: 14,
          name: '人工智能学院第三届“AI创未来”科技创新节前沿学术论坛--大模型之道(郭军教授)',
          category: '学术科创',
          type: 2,
        },
        { id: 15, name: '2022级悠游记忆征集活动', category: '学术科创', type: 2 },
        {
          id: 16,
          name: '计算机学院（国家示范性软件学院）第二十九次研究生代表大会',
          category: '学术科创',
          type: 1,
        },
        { id: 17, name: '”医邮合作，健康传递”手诊活动', category: '文化艺术', type: 3 },
        { id: 18, name: '2023蓝图加速器活动', category: '文化艺术', type: 1 },
        { id: 19, name: '“知识产权”猜灯迷活动', category: '文化艺术', type: 2 },
        {
          id: 20,
          name: '2023“外研社.国才杯”“理解当代中国”全国大学生外语能力竞赛',
          category: '强身健体',
          type: 1,
        },
        { id: 21, name: '第26届科技节开幕式', category: '强身健体', type: 1 },
        { id: 22, name: '探索自我性格与职业规划', category: '强身健体', type: 3 },
        {
          id: 23,
          name: '第十七届北京邮电大学程序设计竞赛校赛',
          category: '其他',
          type: 2,
        },
        { id: 24, name: '2022级校级其他体育比赛', category: '其他', type: 1 },
        {
          id: 25,
          name: '计算机学院2022级党支部单车摆放引导活动',
          category: '其他',
          type: 3,
        },
        {
          id: 26,
          name: '《古籍中的古曲﹣天地英雄》专场音乐会',
          category: '其他',
          type: 3,
        },
        { id: 27, name: '光影悦读——永不消逝的电波', category: '其他', type: 1 },
      ],
    },
  ],
};

const item2 = {
  user: {
    id: 2,
    name: '邮邮邮',
    student_id: '2021211223',
    class_id: '2021211334',
    college: '理学院',
  },
  overall: [
    { category: '参与活动总量', count: 53 },
    { category: '思想成长', count: 3 },
    { category: '社会实践', count: 7 },
    { category: '志愿服务', count: 5 },
    { category: '学术科创', count: 12 },
    { category: '文化艺术', count: 10 },
    { category: '强身健体', count: 7 },
    { category: '其他', count: 9 },
  ],
  semesters: [
    {
      semester: '2021-2022-1',
      acts: [
        { id: 0, name: '北邮红会-爸妈我好想听到你的声音', category: '思想成长', type: 3 },
        { id: 1, name: '2022级“一二·九”火炬接力观众', category: '学术科创', type: 1 },
        {
          id: 2,
          name: '计算机学院本科22级党支部课业辅导组数据库系统原理（ 软件工程）期末考前串讲',
          category: '学术科创',
          type: 1,
        },
        {
          id: 3,
          name: '“智信杯”第二届北京高校学生信息素养大赛开始了！-欢迎访问信息服务门户 (bupt.edu.cn)',
          category: '学术科创',
          type: 2,
        },
        {
          id: 4,
          name: '2024年"邮苑书香 悦读互荐"中文图书展',
          category: '文化艺术',
          type: 3,
        },
        {
          id: 5,
          name: '“国脉传承守初心，扬帆起航铸未来” 2023年学生工作表彰大会学工联欢会',
          category: '文化艺术',
          type: 3,
        },
        { id: 6, name: '北京邮电大学华为鸿蒙公开课', category: '文化艺术', type: 1 },
        { id: 7, name: '篮球1v1挑战赛', category: '强身健体', type: 3 },
        { id: 8, name: '管乐团公开课', category: '其他', type: 1 },
        { id: 9, name: '“秋之韵”歌手大赛', category: '其他', type: 3 },
        { id: 10, name: '学校各部门认定的其他实践劳动', category: '其他', type: 1 },
      ],
    },
    {
      semester: '2021-2022-2',
      acts: [
        { id: 0, name: '篮球1v1挑战赛', category: '思想成长', type: 3 },
        {
          id: 1,
          name: '北京邮电大学第十五届大学生创新创业实践成果展示交流会暨首届”鸿雁杯“学生创新大赛优秀成果展参展项目成员',
          category: '思想成长',
          type: 1,
        },
        { id: 2, name: '2022级体育比赛之“校长杯”足球赛', category: '社 会实践', type: 2 },
        {
          id: 3,
          name: '悦读文化讲堂-光影悦读系列导读《三体》之地球往事',
          category: '志愿服务',
          type: 1,
        },
        {
          id: 4,
          name: '2024年全国大学生电子设计竞赛“瑞萨杯”信息科技前沿专题赛',
          category: '志愿服务',
          type: 1,
        },
        { id: 5, name: '2023北京市大学生艺术节', category: '学术科创', type: 3 },
        {
          id: 6,
          name: '计算机学院本科22级党支部学业辅导组离散数学知识点期中串讲与答疑活动',
          category: '学术科创',
          type: 3,
        },
        { id: 7, name: '西土城校区"1米菜园"劳动实践活动', category: '文化艺术', type: 3 },
        { id: 8, name: '2022级其他校院各类体育活动观众', category: '强身健体', type: 2 },
        { id: 9, name: '2022级体育比赛之“篮俱杯”篮球赛', category: '强身健体', type: 2 },
        {
          id: 10,
          name: '北京邮电大学第三十二届“一二·九”火炬接力赛',
          category: '其他',
          type: 1,
        },
      ],
    },
    {
      semester: '2022-2023-1',
      acts: [
        { id: 0, name: '爱心捐衣捐物', category: '社会实践', type: 1 },
        { id: 1, name: '“艺馨杯”文艺汇演', category: '社会实践', type: 1 },
        { id: 2, name: '管乐交响大艺展比赛', category: '志愿服务', type: 2 },
        { id: 3, name: '2024年全国大学生英语竞赛', category: '志愿 服务', type: 3 },
        { id: 4, name: '“秋之韵”歌手大赛', category: '志愿服务', type: 3 },
        { id: 5, name: '参加抗洪劳动', category: ' 学术科创', type: 2 },
        {
          id: 6,
          name: '【主题创新实践活动】关于举办“WIN 精彩·邮你创”主题创新实践活动之NOLO Unity虚拟展厅系统技术训练营的通知-欢迎访问信息服务门户 (bupt.edu.cn)',
          category: '学术科创',
          type: 3,
        },
        {
          id: 7,
          name: '计算机学院本科2022、2021、2020党支部保研交流分享会',
          category: '其他',
          type: 3,
        },
        {
          id: 8,
          name: '第17届中国大学生计算机设计大赛-北邮选拔赛',
          category: '其他',
          type: 2,
        },
      ],
    },
    {
      semester: '2022-2023-2',
      acts: [
        { id: 0, name: '学科竞赛（团队）', category: '社会实践', type: 1 },
        {
          id: 1,
          name: '“计”承荣光 汲取 力量——听他们讲述计算机人的科研故事',
          category: '学术科创',
          type: 1,
        },
        {
          id: 2,
          name: '2022级心理素质教育工作优秀学生骨干评选',
          category: '学术科创',
          type: 1,
        },
        { id: 3, name: '“一二·九”艺馨杯文艺展演', category: '文化艺术', type: 1 },
        { id: 4, name: 'CCF CSP 计算 机软件能力认证', category: '文化艺术', type: 1 },
        {
          id: 5,
          name: '2024年图书馆第十一届“邮你搜”学术搜索大赛',
          category: '文化艺术',
          type: 2,
        },
        { id: 6, name: '2022级校级十佳宿舍评选', category: '强身健体', type: 1 },
        {
          id: 7,
          name: '大模型时代的泡沫、应用前景与现实瓶颈讲座',
          category: '强身健体',
          type: 2,
        },
        { id: 8, name: '其他校级个人艺术类活动', category: '强身健体', type: 1 },
        { id: 9, name: '2022级优秀班集体评选活动', category: '其他', type: 1 },
      ],
    },
    {
      semester: '2023-2024-1',
      acts: [
        { id: 0, name: '其他校级个人艺术类 活动', category: '社会实践', type: 3 },
        { id: 1, name: '2022级校院升旗仪式', category: '社会实践', type: 1 },
        {
          id: 2,
          name: '“安全之舟，共同护航”线上急救培训活动',
          category: '社会实践',
          type: 1,
        },
        {
          id: 3,
          name: '第48届ICPC国际大学生程序设计竞赛亚洲区域赛（沈阳）',
          category: '学术科创',
          type: 3,
        },
        { id: 4, name: '五月鲜花合唱节', category: '学术科创', type: 1 },
        {
          id: 5,
          name: '其他校院级 征文、朗诵、演讲、作品征集活动',
          category: '学术科创',
          type: 3,
        },
        {
          id: 6,
          name: '计算机学院（国家示范性软件学院）团学组织春季联欢会',
          category: '文化艺术',
          type: 2,
        },
        {
          id: 7,
          name: '计算机学院本科22级党支部学业辅导组离散数学知识点期中串讲与答疑活动',
          category: '文化艺术',
          type: 3,
        },
        {
          id: 8,
          name: '2022级体育比赛之第58届春季运动会',
          category: '文化艺术',
          type: 3,
        },
        {
          id: 9,
          name: '学习强国庆祝 中华人民共和国成立75周年挑战答题活动',
          category: '强身健体',
          type: 1,
        },
        { id: 10, name: '2022级篮球队院队成员', category: '其他', type: 1 },
        {
          id: 11,
          name: '2022级主题教育之朋辈辅导志愿者先进个人评选',
          category: '其他',
          type: 3,
        },
      ],
    },
  ],
};

const item3 = {
  user: {
    id: 3,
    name: '一个数据很少的人',
    student_id: '2023211224',
    class_id: '2023211335',
    college: '未来学院',
  },
  overall: [
    { category: '参与活动总量', count: 12 },
    { category: '思想成长', count: 2 },
    { category: '社会实践', count: 1 },
    { category: '志愿服务', count: 1 },
    { category: '学术科创', count: 2 },
    { category: '文化艺术', count: 0 },
    { category: '强身健体', count: 2 },
    { category: '其他', count: 4 },
  ],
  semesters: [
    {
      semester: '2023-2024-1',
      acts: [
        { id: 0, name: '2022级校级优秀团支部评选', category: '思想成长', type: 2 },
        { id: 1, name: '2023北京市大学生艺术节', category: '思想成长', type: 1 },
        { id: 2, name: '“五月鲜花”合唱比赛', category: '社会实践', type: 3 },
        { id: 3, name: '管乐团公开课', category: '志愿服务', type: 2 },
        {
          id: 4,
          name: '英国皇家工程院院士——The Benefits and Challanges of Self-Supervised Learning',
          category: '学术科创',
          type: 2,
        },
        { id: 5, name: 'live 音乐社冬日专场', category: '其他', type: 1 },
        { id: 6, name: '2024年"邮苑书香 悦读互荐"中文图书展', category: '其他', type: 1 },
      ],
    },
    {
      semester: '2023-2024-2',
      acts: [
        {
          id: 0,
          name: '2022级大二、大三、大四危机干预技术培训',
          category: '学术科创',
          type: 3,
        },
        { id: 1, name: '探索自我性格与职业规划', category: '强身健体', type: 2 },
        {
          id: 2,
          name: '“邮为少年 奔赴山海”北京邮电大学第三十七届校园歌手大赛',
          category: '强身健体',
          type: 3,
        },
        {
          id: 3,
          name: '2022级主题教育之计言心声座谈会-数据科学与大数据技术专业',
          category: '其他',
          type: 3,
        },
        {
          id: 4,
          name: '“扇传邮意，珠慰母心—— 一珠一扇 总关情”母亲节活动',
          category: '其他',
          type: 3,
        },
      ],
    },
  ],
};

const datas = [item1, item2, item3];

export default datas;
